# pubspec.yaml
name: hotel_review_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


  firebase_core: ^3.14.0 
  firebase_auth: ^5.6.0 
  cloud_firestore: ^5.6.9 
  firebase_storage: ^12.1.1 
  image_picker: ^1.0.7 
  geolocator: ^14.0.1 
  google_maps_flutter: ^2.5.3 
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 
  http: ^1.2.1

  geocoding: ^4.0.0

  flutter_rating_bar: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
        - asset: fonts/Inter_18pt-Bold.ttf
          weight: 700