// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorO-UJMqwPHMxUVU7_yidK9_GTWLP9W8',
    appId: '1:132448896320:web:e376802a316265bd2fe6a5',
    messagingSenderId: '132448896320',
    projectId: 'proyekuaspab2',
    authDomain: 'proyekuaspab2.firebaseapp.com',
    databaseURL: 'https://proyekuaspab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekuaspab2.firebasestorage.app',
    measurementId: 'G-FGHN33VL2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNYfw-zai5SEG5V2NjnXqs23aODCn91GE',
    appId: '1:132448896320:android:31662105ca72472a2fe6a5',
    messagingSenderId: '132448896320',
    projectId: 'proyekuaspab2',
    databaseURL: 'https://proyekuaspab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekuaspab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Ipcdb6d4K9xnou9pYdQFxEtIZUJx3FA',
    appId: '1:132448896320:ios:246329c713989ba82fe6a5',
    messagingSenderId: '132448896320',
    projectId: 'proyekuaspab2',
    databaseURL: 'https://proyekuaspab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekuaspab2.firebasestorage.app',
    iosBundleId: 'com.example.hotelReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Ipcdb6d4K9xnou9pYdQFxEtIZUJx3FA',
    appId: '1:132448896320:ios:246329c713989ba82fe6a5',
    messagingSenderId: '132448896320',
    projectId: 'proyekuaspab2',
    databaseURL: 'https://proyekuaspab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekuaspab2.firebasestorage.app',
    iosBundleId: 'com.example.hotelReviewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorO-UJMqwPHMxUVU7_yidK9_GTWLP9W8',
    appId: '1:132448896320:web:32834b80d82ab4002fe6a5',
    messagingSenderId: '132448896320',
    projectId: 'proyekuaspab2',
    authDomain: 'proyekuaspab2.firebaseapp.com',
    databaseURL: 'https://proyekuaspab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'proyekuaspab2.firebasestorage.app',
    measurementId: 'G-44RHL8GY60',
  );

}